
language: ruby
sudo: false
cache: bundler
rvm:
- 2.2.5
- 2.2.4
deploy:
  provider: heroku
  api_key:
    secure: "d6nAhl4WS5GOMCRBa9T6KGRYn4BK8V9Lv+fAR3CeFGWkMrKuqlvZXycxejp1oCYhHylQouZJfVo2M45vAdweNZM/GZDC1oShc0LGn/JqHHFflnCjR8OJFL+8mk5QZw6S/lR/kw95/VZXNy9oHrhcEEI3EyvBtARZpyHHacvBn83IV/+KikN3hEhccgl1ZXrSBt86I+f63A/PZzc3DIwaF7HpMJ6sF7ooBSXHcHjAmYguP6DbKqwee0IpY0V5uD7EjnHLcmvaTHPQoWko5XveLF9ZevPzglSUGiMEd9aubV4GGEf/gTg7Ic4RNvAoXyDjmxYR7GS/1FjwkwVWts3NwiojJTvnt5gAcHNYfxNQTFd91/phsDo2qcg6hA9QjPF71BZna0bwoJdK5ByaF3iOwWVClNhz/oRuKqNfKNpqLqxWz9OFStvA5E9qq85zQalLZRRR+bC/1hxt7X4XvfDYsBtBFRe2i4bt5mlAn8ADuafyUqtRCZIzPDuleyOfi6Y6zKBX/AmMgqf1GXUI6uPujrxQ7E2Ap+uLrZiwp9jvJifo9+KnMd+1Sl7tLljjDXbkAbZi6HlmzfNl0REqMFVH4Q7vD/tKX+V21efAM/ubyg4yWYfNTriAiUNimT6CH+n99clBubQPmKIvBFShT51fmWobw4zNeM3Q+ntO2cRG85o="
